# Generated by Django 3.2.4 on 2021-06-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, default='Samir', max_length=100, null=True)),
            ],
        ),
    ]
